version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]
    ports:
      - "8080:8080"
    volumes:
      - ./envoy-config.yaml:/etc/envoy/envoy.yaml
      - ./extensions/payload-otlp/build/otlp_capture_payload.wasm:/etc/istio/extensions/otlp_capture_payload.wasm
